upstream backend {
    server backend:8080;
}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend;
    }

    location /api/v1/swagger-ui/ {
        proxy_pass http://backend;
    }

    location /api/v1/api-docs {
        proxy_pass http://backend;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
